language: php

php:
  - 5.3
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer install
  - npm install
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
  - phpunit
  - npm test
