version: '2'
services:
  wordpress:
    build: .
    image: phpcompat/plugin
    restart: always
    depends_on:
      - db
    links:
    - db:mysql
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html/wp-content/plugins/phpcompat
      - ./helpers/phpcompat_filters.php:/var/www/html/wp-content/mu-plugins/phpcompat_filters.php:ro

    environment:
      WORDPRESS_DB_PASSWORD: password
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
